version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/test.db
      - chroma_data:/app/app/chroma_db
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - study_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - study_network

volumes:
  sqlite_data:
  chroma_data:

networks:
  study_network:
    driver: bridge
